### ISSUE TITLE
Remove HelveticaNeueInterface-MediumP4 from default styles

### ISSUE THREAD

**Issue by outaTiME** [react-native-component/react-native-smart-corner-label#1]
Hi, It would be nice to remove the default `HelveticaNeueInterface-MediumP4` from fontFamily definition in text styles, it fails running on expo.io.

Thanks !!!

**Comment by cyqresig** [comment]
Dear outaTiME,
You can set the 'textStyle' props to rewrite fontFamily style.

**Comment by outaTiME** [comment]
Hi, yup ... it was the first thing i tried to do but doesn't work ... take a look:

```js
<CornerLabel
  cornerRadius={66}
  alignment={'right'}
  style={{backgroundColor: 'red', height: 24, }}
  textStyle={{color: '#fff', fontSize: 12, fontFamily: 'Avenir'}}>
  PROMO
</CornerLabel>
```

![screen shot 2017-06-14 at 1 56 18 pm](https://user-images.githubusercontent.com/140472/27144729-5e20e5ee-5109-11e7-9648-74868374846f.png)

**Comment by cyqresig** [comment]
As your wish,  'HelveticaNeueInterface-MediumP4' fontFamily style has been removed. You can upgrade to version 1.1.2

**Comment by outaTiME** [comment]
Thanks @cyqresig, works as expected !!!
